### PR TITLE
Implement collapsibles on sidebar menu

### PR DESCRIPTION
**Pull request by danisztls**
Follow up #12

### CODE REVIEW

**Comment by marina-chibizova** [comment]
`Custodians` may extend dramatically in the future. let's make sure they are not cluttering the outline and the list only appears on the page opening by click. The same may be applied to `Categories`

**Comment by danisztls** [comment]
@marina-chibizova What I have in mind is to have the level 4 sections (`Categories` & `Custodians`) collapsed by default but expanded if they are part of the current page path.

Like this:

Screenshot from 2023-05-15 07-41-25
Screenshot from 2023-05-15 07-41-38

**Comment by marina-chibizova** [comment]
It's good, but we may have hundreds of custodians at some point. even as a collapsible, it will be too much for a menu. I would instead show this taxonomy on a page

**Comment by danisztls** [comment]
Ok. Will write a rule to not list sections with more than 7 items.

**Comment by marina-chibizova** [comment]
why 7? maybe just hide sections on this level of menu (I believe it's 4th) and only show higher level menu items? and list the details on pages. wouldn't it be easier and more straightforward logic?

**Comment by danisztls** [comment]
> why 7?

No special reason. Can be 3 or any number.

> maybe just hide sections on this level of menu (I believe it's 4th) and only show higher level menu items? and list the details on pages. wouldn't it be easier and more straightforward logic?

Both ways are straightforward. I can comment the terms subsection or add a conditional statement. "Custodians" & "Categories" are on the same level. Wasn't an initial goal to have "Categories" expanded?

**Comment by marina-chibizova** [comment]
I believe it's ok to not have `Categories` expanded, since we have them on the page + in the ToC on the right-hand side. No need to duplicate it in the main menu

**Review by marina-chibizova — APPROVED** [review]

**Pull request merged**
