### PR TITLE
Fix content path

### PR DESCRIPTION
**Pull request by danisztls**
There was a trailing space in the directory name.

### CODE REVIEW

**Comment by danisztls** [comment]
Suggestion: remove the post date from the file names because Hugo don't use.

**Comment by evgenydmitriev** [comment]
Why are you deleting `content/attacks/posts/2019-01-05-Ethereum-Classic.md`?

**Comment by danisztls** [comment]
@evgenydmitriev I thought it was an update meant to replace the older post but I was wrong.

**Comment by danisztls** [comment]
Rebased, restoring the deleted file.

**Pull request merged**
