### PR TITLE
Bitcoin Gold suffers a 51% attack again

### PR DESCRIPTION
**Pull request by Joe-Vitara**

### CODE REVIEW

**Review by jhirschkorn — CHANGES_REQUESTED** [review]
are there any additional points of importance on the timeline?

**Comment by Joe-Vitara** [comment]
Found just 'Binance increases escrow periods' info, in addition.

**Review by Joe-Vitara — COMMENTED** [review]
Added Binance increases escrow periods into the timeline

**Review by jhirschkorn — APPROVED** [review]

**Review by jhirschkorn — APPROVED** [review]

**Comment by jhirschkorn** [comment]
what is going on here?  articles are all mixed up.  doesnt make sense.

**Comment by jhirschkorn** [comment]
> Did not quite catch you, I've committed just 1 article. If it was made in the wrong way, I am sorry and would appreciate if you can provide explanations/comments

sorry, my fault. looked at the wrong thing and got confused. merging.

**Pull request merged**
